"""Template ForecastBot adapter. Runtime SDK integration must pass Test Bot."""  # GLUE (NOT EXECUTED offline)
import argparse  # GLUE (NOT EXECUTED offline)
import asyncio  # GLUE (NOT EXECUTED offline)
import json  # GLUE (NOT EXECUTED offline)
import logging  # GLUE (NOT EXECUTED offline)
import os  # GLUE (NOT EXECUTED offline)
import threading  # GLUE (NOT EXECUTED offline)
import forecasting_tools  # GLUE (NOT EXECUTED offline)
import bot_helpers  # GLUE (NOT EXECUTED offline)
from concurrent.futures import TimeoutError as FutureTimeout  # GLUE (NOT EXECUTED offline)
from types import SimpleNamespace  # GLUE (NOT EXECUTED offline)
from datetime import datetime, timezone  # GLUE (NOT EXECUTED offline)
from urllib.parse import urlsplit  # GLUE (NOT EXECUTED offline)
from forecasting_tools import (  # GLUE (NOT EXECUTED offline)
    ForecastBot, BinaryQuestion, MultipleChoiceQuestion, NumericQuestion,  # GLUE (NOT EXECUTED offline)
    DateQuestion, ConditionalQuestion, NumericDistribution, Percentile,  # GLUE (NOT EXECUTED offline)
    PredictedOptionList, BinaryPrediction, ReasonedPrediction, GeneralLlm, structure_output,  # GLUE (NOT EXECUTED offline)
)  # GLUE (NOT EXECUTED offline)
from fbot import SkipQuestion, CreditExhausted, ModelFailure  # GLUE (NOT EXECUTED offline)
from fbot.config import SEASON_ID, MINIBENCH_ID, TEST_ID, OPUS, SOL, FLASH, CHEAP, BRIDGE, PROBES, enabled, model_slots  # GLUE (NOT EXECUTED offline)
from fbot import comment, parse, runloop, targets, validate  # GLUE (NOT EXECUTED offline)
from fbot.budget import Pacer, configure_preset, log_preset  # GLUE (NOT EXECUTED offline)
from fbot.llm import Client, transport  # GLUE (NOT EXECUTED offline)
from fbot.metadata import open_count, already_forecast, readback  # GLUE (NOT EXECUTED offline)
from fbot import live, schedule, ledger, probe, config, numeric, numeric_path  # GLUE (NOT EXECUTED offline)
from fbot.io_limits import call_scope, bounded_timeout  # GLUE (NOT EXECUTED offline)
from fbot.pipeline import Dependencies, forecast_async  # GLUE (NOT EXECUTED offline)
from fbot.priority import PriorityLimiter  # GLUE (NOT EXECUTED offline)
from fbot.postgate import Gate  # GLUE (NOT EXECUTED offline)
from fbot.research import Service, error_code  # GLUE (NOT EXECUTED offline)
from fbot.state import RunState  # GLUE (NOT EXECUTED offline)
from fbot.types import Clock, Question  # GLUE (NOT EXECUTED offline)

logger = logging.getLogger("fbot")  # GLUE (NOT EXECUTED offline)
_fallbacks = set()  # GLUE (NOT EXECUTED offline)
_fallback_lock = threading.Lock()  # GLUE (NOT EXECUTED offline)


def attribute(obj, name, default=None):  # GLUE (NOT EXECUTED offline)
    sentinel = object()  # GLUE (NOT EXECUTED offline)
    value = getattr(obj, name, sentinel)  # GLUE (NOT EXECUTED offline)
    if value is sentinel:  # GLUE (NOT EXECUTED offline)
        with _fallback_lock:  # GLUE (NOT EXECUTED offline)
            key = type(obj).__name__ + "." + name  # GLUE (NOT EXECUTED offline)
            if key not in _fallbacks:  # GLUE (NOT EXECUTED offline)
                _fallbacks.add(key)  # GLUE (NOT EXECUTED offline)
                logger.info("GLUE-FALLBACK %s", key)  # GLUE (NOT EXECUTED offline)
        return default  # GLUE (NOT EXECUTED offline)
    return value  # GLUE (NOT EXECUTED offline)


class SafeLog(logging.Filter):  # GLUE (NOT EXECUTED offline)
    def filter(self, record):  # GLUE (NOT EXECUTED offline)
        if not record.name.startswith("fbot"):  # GLUE (NOT EXECUTED offline)
            record.msg, record.args = "DEPENDENCY_WARNING", ()  # GLUE (NOT EXECUTED offline)
            record.exc_info, record.exc_text, record.stack_info = None, None, None  # GLUE (NOT EXECUTED offline)
        return True  # GLUE (NOT EXECUTED offline)


def setup_logs():  # GLUE (NOT EXECUTED offline)
    logging.basicConfig(level=logging.WARNING, format="%(message)s", force=True)  # GLUE (NOT EXECUTED offline)
    for handler in logging.getLogger().handlers:  # GLUE (NOT EXECUTED offline)
        handler.addFilter(SafeLog())  # GLUE (NOT EXECUTED offline)
    for name in ("forecasting_tools", "litellm", "__main__"):  # GLUE (NOT EXECUTED offline)
        logging.getLogger(name).setLevel(logging.WARNING)  # GLUE (NOT EXECUTED offline)
    logger.setLevel(logging.INFO)  # GLUE (NOT EXECUTED offline)


def install_post_gate(gate):  # GLUE (NOT EXECUTED offline)
    # Both clients are in the unchanged dependency lock. The gate itself is stdlib-tested.  # GLUE (NOT EXECUTED offline)
    import requests  # GLUE (NOT EXECUTED offline)
    import httpx  # GLUE (NOT EXECUTED offline)
    original_send = requests.Session.send  # GLUE (NOT EXECUTED offline)

    def requests_send(session, request, **kwargs):  # GLUE (NOT EXECUTED offline)
        data, ticket = gate.before(request.method, request.url, request.body)  # GLUE (NOT EXECUTED offline)
        if ticket:  # GLUE (NOT EXECUTED offline)
            request.body = json.dumps(data).encode()  # GLUE (NOT EXECUTED offline)
            request.headers["Content-Length"] = str(len(request.body))  # GLUE (NOT EXECUTED offline)
            request.headers["Content-Type"] = "application/json"  # GLUE (NOT EXECUTED offline)
        kwargs["timeout"] = bounded_timeout(kwargs.get("timeout"), gate.state.clock)  # GLUE (NOT EXECUTED offline)
        try:  # GLUE (NOT EXECUTED offline)
            response = original_send(session, request, **kwargs)  # GLUE (NOT EXECUTED offline)
        except Exception:  # GLUE (NOT EXECUTED offline)
            gate.after(ticket, 0)  # GLUE (NOT EXECUTED offline)
            raise  # GLUE (NOT EXECUTED offline)
        gate.after(ticket, response.status_code)  # GLUE (NOT EXECUTED offline)
        return response  # GLUE (NOT EXECUTED offline)

    requests.Session.send = requests_send  # GLUE (NOT EXECUTED offline)
    original_sync = httpx.Client.send  # GLUE (NOT EXECUTED offline)
    original_async = httpx.AsyncClient.send  # GLUE (NOT EXECUTED offline)

    def checked_request(request):  # GLUE (NOT EXECUTED offline)
        timeouts = request.extensions.get("timeout", {})  # GLUE (NOT EXECUTED offline)
        request.extensions["timeout"] = {name: bounded_timeout(timeouts.get(name), gate.state.clock)  # GLUE (NOT EXECUTED offline)
                                         for name in ("connect", "read", "write", "pool")}  # GLUE (NOT EXECUTED offline)
        data, ticket = gate.before(request.method, str(request.url), request.content)  # GLUE (NOT EXECUTED offline)
        if ticket:  # GLUE (NOT EXECUTED offline)
            headers = dict(request.headers)  # GLUE (NOT EXECUTED offline)
            headers.pop("content-length", None)  # GLUE (NOT EXECUTED offline)
            request = httpx.Request(request.method, request.url, headers=headers,  # GLUE (NOT EXECUTED offline)
                                    json=data, extensions=request.extensions)  # GLUE (NOT EXECUTED offline)
        return request, ticket  # GLUE (NOT EXECUTED offline)

    def sync_send(client, request, **kwargs):  # GLUE (NOT EXECUTED offline)
        request, ticket = checked_request(request)  # GLUE (NOT EXECUTED offline)
        try:  # GLUE (NOT EXECUTED offline)
            response = original_sync(client, request, **kwargs)  # GLUE (NOT EXECUTED offline)
        except Exception:  # GLUE (NOT EXECUTED offline)
            gate.after(ticket, 0)  # GLUE (NOT EXECUTED offline)
            raise  # GLUE (NOT EXECUTED offline)
        gate.after(ticket, response.status_code)  # GLUE (NOT EXECUTED offline)
        return response  # GLUE (NOT EXECUTED offline)

    async def async_send(client, request, **kwargs):  # GLUE (NOT EXECUTED offline)
        request, ticket = await asyncio.to_thread(checked_request, request)  # GLUE (NOT EXECUTED offline)
        try:  # GLUE (NOT EXECUTED offline)
            response = await original_async(client, request, **kwargs)  # GLUE (NOT EXECUTED offline)
        except Exception:  # GLUE (NOT EXECUTED offline)
            gate.after(ticket, 0)  # GLUE (NOT EXECUTED offline)
            raise  # GLUE (NOT EXECUTED offline)
        gate.after(ticket, response.status_code)  # GLUE (NOT EXECUTED offline)
        return response  # GLUE (NOT EXECUTED offline)

    httpx.Client.send, httpx.AsyncClient.send = sync_send, async_send  # GLUE (NOT EXECUTED offline)


def ask_news(query, auth, timeout, strategy, n_articles, parity=False, now=None):  # GLUE (NOT EXECUTED offline)
    from asknews_sdk import AskNewsSDK  # GLUE (NOT EXECUTED offline)
    from concurrent.futures import ThreadPoolExecutor  # GLUE (NOT EXECUTED offline)
    # The pair/scopes/search pattern is visible in the cloned no-framework example.  # GLUE (NOT EXECUTED offline)
    ask = AskNewsSDK(**auth, scopes={"news"})  # GLUE (NOT EXECUTED offline)
    pool = ThreadPoolExecutor(max_workers=1)  # GLUE (NOT EXECUTED offline)
    future = pool.submit(ask.news.search_news, query=query, n_articles=n_articles,  # GLUE (NOT EXECUTED offline)
                         return_type="both", strategy=strategy)  # GLUE (NOT EXECUTED offline)
    try:  # GLUE (NOT EXECUTED offline)
        response = future.result(timeout=timeout)  # GLUE (NOT EXECUTED offline)
        articles = attribute(response, "as_dicts", []) or []  # GLUE (NOT EXECUTED offline)
        rows, source_rows = [], []  # GLUE (NOT EXECUTED offline)
        for entry in articles:  # GLUE (NOT EXECUTED offline)
            item = entry if isinstance(entry, dict) else attribute(entry, "__dict__", {})  # GLUE (NOT EXECUTED offline)
            source_rows.append(item)  # GLUE (NOT EXECUTED offline)
            if parity:  # GLUE (NOT EXECUTED offline)
                from fbot.edge import article  # GLUE (NOT EXECUTED offline)
                rows.append(article(item))  # GLUE (NOT EXECUTED offline)
            else:  # GLUE (NOT EXECUTED offline)
                rows.append(str(item.get("eng_title", "")) + "\n" + str(item.get("summary", "")) +  # GLUE (NOT EXECUTED offline)
                            "\n" + str(item.get("article_url", "")))  # GLUE (NOT EXECUTED offline)
        if parity:  # GLUE (NOT EXECUTED offline)
            from fbot.edge import article_counts  # GLUE (NOT EXECUTED offline)
            article_counts(source_rows, now)  # GLUE (NOT EXECUTED offline)
        return "\n\n".join(rows), len(rows)  # GLUE (NOT EXECUTED offline)
    finally:  # GLUE (NOT EXECUTED offline)
        future.cancel()  # GLUE (NOT EXECUTED offline)
        pool.shutdown(wait=False, cancel_futures=True)  # GLUE (NOT EXECUTED offline)


from fbot import evidence, research2, sources, markets, webread  # GLUE (NOT EXECUTED offline)
from fbot.types import Research  # GLUE (NOT EXECUTED offline)
from fbot.research2 import WebResearch  # GLUE (NOT EXECUTED offline)
from fbot.sources import Reader as SourcesReader  # GLUE (NOT EXECUTED offline)
from fbot.markets import Markets  # GLUE (NOT EXECUTED offline)
from concurrent.futures import ThreadPoolExecutor  # GLUE (NOT EXECUTED offline)


class FBot(ForecastBot):  # GLUE (NOT EXECUTED offline)
    _max_concurrent_questions = 5  # GLUE (NOT EXECUTED offline)
    _concurrency_limiter = asyncio.Semaphore(_max_concurrent_questions)  # GLUE (NOT EXECUTED offline)

    def setup(self, env, state, client, pacer, research, gate, test=False, main_loop=None, research_limiter=None):  # GLUE (NOT EXECUTED offline)
        self.f_env, self.f_state, self.f_client = env, state, client  # GLUE (NOT EXECUTED offline)
        self.f_pacer, self.f_research, self.f_gate = pacer, research, gate  # GLUE (NOT EXECUTED offline)
        self.f_clock = state.clock  # GLUE (NOT EXECUTED offline)
        numeric_path.configured(env, state)  # GLUE (NOT EXECUTED offline)
        self.f_test, self.f_target = test, "test" if test else "season"  # GLUE (NOT EXECUTED offline)
        self.f_loop = main_loop  # GLUE (NOT EXECUTED offline)
        self.f_loop_minutes = 45  # GLUE (NOT EXECUTED offline)
        self.f_research_limiter = research_limiter or PriorityLimiter(2)  # GLUE (NOT EXECUTED offline)
        self.f_evidence = {}  # GLUE (NOT EXECUTED offline)
        self.f_evidence_services = None  # GLUE (NOT EXECUTED offline)
        self.f_test_research_done = False  # GLUE (NOT EXECUTED offline)
        self.f_context = {}  # GLUE (NOT EXECUTED offline)
        self.f_seen = set()  # GLUE (NOT EXECUTED offline)
        self.f_questions = {}  # GLUE (NOT EXECUTED offline)

    def question(self, raw):  # GLUE (NOT EXECUTED offline)
        if isinstance(raw, (DateQuestion, ConditionalQuestion)):  # GLUE (NOT EXECUTED offline)
            raise SkipQuestion("UNHANDLED_TYPE")  # GLUE (NOT EXECUTED offline)
        discrete = isinstance(raw, getattr(forecasting_tools, "DiscreteQuestion", ()))  # GLUE (NOT EXECUTED offline)
        kind = ("binary" if isinstance(raw, BinaryQuestion) else  # GLUE (NOT EXECUTED offline)
                "multiple_choice" if isinstance(raw, MultipleChoiceQuestion) else  # GLUE (NOT EXECUTED offline)
                "numeric" if isinstance(raw, NumericQuestion) or discrete else "unsupported")  # GLUE (NOT EXECUTED offline)
        if kind == "unsupported":  # GLUE (NOT EXECUTED offline)
            raise SkipQuestion("UNHANDLED_TYPE")  # GLUE (NOT EXECUTED offline)
        qid, post_id = attribute(raw, "id_of_question"), attribute(raw, "id_of_post")  # GLUE (NOT EXECUTED offline)
        if not isinstance(qid, int) or not isinstance(post_id, int):  # GLUE (NOT EXECUTED offline)
            raise SkipQuestion("INVALID_OUTPUT")  # GLUE (NOT EXECUTED offline)
        numeric = kind == "numeric"  # GLUE (NOT EXECUTED offline)
        count, size_known = 200, True  # GLUE (NOT EXECUTED offline)
        if numeric:  # GLUE (NOT EXECUTED offline)
            inbound = attribute(raw, "inbound_outcome_count", None)  # GLUE (NOT EXECUTED offline)
            cdf_size = attribute(raw, "cdf_size", None) if not inbound else None  # GLUE (NOT EXECUTED offline)
            count = inbound or ((cdf_size or 201) - 1)  # GLUE (NOT EXECUTED offline)
            size_known = bool(inbound or cdf_size)  # GLUE (NOT EXECUTED offline)
            if discrete or count != 200:  # GLUE (NOT EXECUTED offline)
                kind = "discrete"  # GLUE (NOT EXECUTED offline)
        close = attribute(raw, "close_time") or attribute(raw, "scheduled_close_time")  # GLUE (NOT EXECUTED offline)
        try:  # GLUE (NOT EXECUTED offline)
            close = targets.utc(close) if close else None  # GLUE (NOT EXECUTED offline)
        except (TypeError, ValueError, AttributeError):  # GLUE (NOT EXECUTED offline)
            close = None  # GLUE (NOT EXECUTED offline)
        return Question(qid, post_id, kind, raw.question_text, self.f_target,  # GLUE (NOT EXECUTED offline)
                        background=raw.background_info or "", resolution=raw.resolution_criteria or "",  # GLUE (NOT EXECUTED offline)
                        fine_print=raw.fine_print or "",  # GLUE (NOT EXECUTED offline)
                        options=tuple(attribute(raw, "options", []) or []) if kind == "multiple_choice" else (),  # GLUE (NOT EXECUTED offline)
                        lower=attribute(raw, "lower_bound", 0) if numeric else 0,  # GLUE (NOT EXECUTED offline)
                        upper=attribute(raw, "upper_bound", 100) if numeric else 100,  # GLUE (NOT EXECUTED offline)
                        open_lower=attribute(raw, "open_lower_bound", False) if numeric else False,  # GLUE (NOT EXECUTED offline)
                        open_upper=attribute(raw, "open_upper_bound", False) if numeric else False,  # GLUE (NOT EXECUTED offline)
                        zero_point=attribute(raw, "zero_point") if numeric else None,  # GLUE (NOT EXECUTED offline)
                        inbound_outcome_count=count, size_known=size_known,  # GLUE (NOT EXECUTED offline)
                        unit=(attribute(raw, "unit_of_measure", "") or "") if numeric else "", close_time=close,  # GLUE (NOT EXECUTED offline)
                        resolve_time=attribute(raw, "scheduled_resolution_time", None) or  # GLUE (NOT EXECUTED offline)
                        attribute(raw, "scheduled_resolve_time", None))  # GLUE (NOT EXECUTED offline)

    def standin(self, raw):  # GLUE (NOT EXECUTED offline)
        qid = attribute(raw, "id_of_question")  # GLUE (NOT EXECUTED offline)
        return SimpleNamespace(qid=qid if isinstance(qid, int) else "unknown", target=self.f_target)  # GLUE (NOT EXECUTED offline)

    async def run_research(self, raw):  # GLUE (NOT EXECUTED offline)
        question, memo = self.standin(raw), False  # GLUE (NOT EXECUTED offline)
        self.f_state.mark_seen(question)  # GLUE (NOT EXECUTED offline)
        try:  # GLUE (NOT EXECUTED offline)
            question = self.question(raw)  # GLUE (NOT EXECUTED offline)
            self.f_seen.add(question.qid)  # GLUE (NOT EXECUTED offline)
            self.f_questions[question.qid] = question  # GLUE (NOT EXECUTED offline)
            if question.qid in self.f_state.posted:  # GLUE (NOT EXECUTED offline)
                self.f_state.counts["memo_hits"] += 1  # GLUE (NOT EXECUTED offline)
                memo = True  # GLUE (NOT EXECUTED offline)
                raise SkipQuestion("ALREADY_FORECAST")  # GLUE (NOT EXECUTED offline)
            if self.f_state.failures[question.qid] >= 2:  # GLUE (NOT EXECUTED offline)
                raise SkipQuestion("RETRY_CAPPED")  # GLUE (NOT EXECUTED offline)
            if not self.f_test and not targets.active(self.f_clock.now(), self.f_env):  # GLUE (NOT EXECUTED offline)
                raise SkipQuestion("AFTER_SEASON")  # GLUE (NOT EXECUTED offline)
            details = {}  # GLUE (NOT EXECUTED offline)
            found = await asyncio.to_thread(already_forecast, question.post_id, question.qid, self.f_env, details=details)  # GLUE (NOT EXECUTED offline)
            question.is_group = bool(details.get("group", question.is_group))  # GLUE (NOT EXECUTED offline)
            logger.info("READBACK qid=%s state=%s why=%s group=%s", question.qid,  # GLUE (NOT EXECUTED offline)
                        "found" if found is True else "none" if found is False else "unknown",  # GLUE (NOT EXECUTED offline)
                        details.get("why", "shape" if found is None else "ok"), int(question.is_group))  # GLUE (NOT EXECUTED offline)
            if question.target != "test":  # GLUE (NOT EXECUTED offline)
                if found is True:  # GLUE (NOT EXECUTED offline)
                    raise SkipQuestion("ALREADY_FORECAST")  # GLUE (NOT EXECUTED offline)
                if found is None:  # GLUE (NOT EXECUTED offline)
                    if question.is_group:  # GLUE (NOT EXECUTED offline)
                        self.f_state.counts["readback_unknown_group"] += 1  # GLUE (NOT EXECUTED offline)
                    self.f_state.counts["gate_blocks"] += 1  # GLUE (NOT EXECUTED offline)
                    self.f_state.alert("GATE_BLOCKED")  # GLUE (NOT EXECUTED offline)
                    logger.warning("GATE_BLOCK qid=%s kind=forecast rule=readback", question.qid)  # GLUE (NOT EXECUTED offline)
                    raise SkipQuestion("READBACK_UNKNOWN")  # GLUE (NOT EXECUTED offline)
            try:  # GLUE (NOT EXECUTED offline)
                allowance = schedule.budget(question, self.f_clock, self.f_state.job_started)  # GLUE (NOT EXECUTED offline)
                end, urgent = allowance.deadline, allowance.fast  # GLUE (NOT EXECUTED offline)
            except SkipQuestion:  # GLUE (NOT EXECUTED offline)
                raise  # GLUE (NOT EXECUTED offline)
            except Exception as error:  # GLUE (NOT EXECUTED offline)
                logger.info("BUDGET error=%s", type(error).__name__)  # GLUE (NOT EXECUTED offline)
                self.f_state.without_modules.add("schedule")  # GLUE (NOT EXECUTED offline)
                end, urgent = runloop.deadline(question, self.f_clock, self.f_state.job_started)  # GLUE (NOT EXECUTED offline)
            tier = self.f_pacer.tier(question, fast=urgent)  # GLUE (NOT EXECUTED offline)
            async with self.f_research_limiter.slot(question):  # GLUE (NOT EXECUTED offline)
                web, pages, snapshot = research2.WebBrief(), sources.PagesBrief(), markets.MarketsBrief()  # GLUE (NOT EXECUTED offline)
                if self.f_evidence_services is None:  # GLUE (NOT EXECUTED offline)
                    research = await asyncio.to_thread(self.f_research.get, question, end)  # GLUE (NOT EXECUTED offline)
                else:  # GLUE (NOT EXECUTED offline)
                    tally, reader, web_service, market_service, pool = self.f_evidence_services  # GLUE (NOT EXECUTED offline)
                    allowed = self.f_test and not self.f_test_research_done  # GLUE (NOT EXECUTED offline)
                    self.f_test_research_done = self.f_test_research_done or self.f_test  # GLUE (NOT EXECUTED offline)
                    if not self.f_test and schedule.switch(self.f_env, "RESEARCH2_ENABLED"):  # GLUE (NOT EXECUTED offline)
                        allowed = self.f_pacer.reserve_web(question, urgent)  # GLUE (NOT EXECUTED offline)
                    loop = asyncio.get_running_loop()  # GLUE (NOT EXECUTED offline)
                    def submit(name, fn, fallback, *args):  # GLUE (NOT EXECUTED offline)
                        return loop.run_in_executor(pool, evidence.call, name, fn, fallback, self.f_state, *args)  # GLUE (NOT EXECUTED offline)
                    research, web, pages, snapshot = await asyncio.gather(  # GLUE (NOT EXECUTED offline)
                        asyncio.to_thread(evidence.call, "research", self.f_research.get, Research(), self.f_state, question, end),  # GLUE (NOT EXECUTED offline)
                        submit("research2", web_service.brief, web, question, end, allowed),  # GLUE (NOT EXECUTED offline)
                        submit("sources", reader.read, pages, question, end),  # GLUE (NOT EXECUTED offline)
                        submit("markets", market_service.snapshot, snapshot, question, end))  # GLUE (NOT EXECUTED offline)
                    evidence.sync(tally, self.f_state)  # GLUE (NOT EXECUTED offline)
                    if web.cost_usd is not None and question.qid not in self.f_evidence:  # GLUE (NOT EXECUTED offline)
                        self.f_state.remember("record_spend", "RESEARCH2", web.cost_usd, self.f_clock.now())  # GLUE (NOT EXECUTED offline)
                    logger.info("PAGES qid=%s tried=%s ok=%s", question.qid, pages.tried, pages.ok)  # GLUE (NOT EXECUTED offline)
                    logger.info("%s", research2.cost_line(web))  # GLUE (NOT EXECUTED offline)
                self.f_evidence[question.qid] = (web, pages, snapshot)  # GLUE (NOT EXECUTED offline)
                if not research.available:  # GLUE (NOT EXECUTED offline)
                    self.f_state.research_calls["none"] += 1  # GLUE (NOT EXECUTED offline)
                if enabled(self.f_env, "SKIP_WITHOUT_RESEARCH") and not research.available and not web.available and not self.f_state.without_modules:  # GLUE (NOT EXECUTED offline)
                    raise SkipQuestion("NO_RESEARCH")  # GLUE (NOT EXECUTED offline)
            self.f_context[question.qid] = (question, research, tier, end, urgent)  # GLUE (NOT EXECUTED offline)
            logger.info("RESEARCH qid=%s status=%s articles=%s error=%s", question.qid,  # GLUE (NOT EXECUTED offline)
                        research2.research_line(research.available, research.articles, web), research.articles,  # GLUE (NOT EXECUTED offline)
                        getattr(self.f_research, "errors", {}).get(question.qid, "-"))  # GLUE (NOT EXECUTED offline)
            return research.text  # GLUE (NOT EXECUTED offline)
        except SkipQuestion as skip:  # GLUE (NOT EXECUTED offline)
            if not memo:  # GLUE (NOT EXECUTED offline)
                release = getattr(self.f_pacer, "release", None)  # GLUE (NOT EXECUTED offline)
                if callable(release):  # GLUE (NOT EXECUTED offline)
                    release(question.qid)  # GLUE (NOT EXECUTED offline)
                self.f_state.skip(question, skip.reason)  # GLUE (NOT EXECUTED offline)
            raise  # GLUE (NOT EXECUTED offline)

    async def structure(self, question, text, output_type, tier=None, instructions=""):  # GLUE (NOT EXECUTED offline)
        from fbot.keys import NAMES  # GLUE (NOT EXECUTED offline)
        context = self.f_context.get(question.qid)  # GLUE (NOT EXECUTED offline)
        deadline = context[3] if context else None  # GLUE (NOT EXECUTED offline)
        direct = tier == "BRIDGE" or (not self.f_env.get("OPENROUTER_API_KEY") and not self.f_env.get("OPENROUTER_API_KEY_OWN"))  # GLUE (NOT EXECUTED offline)
        attempted = set()  # GLUE (NOT EXECUTED offline)
        while True:  # GLUE (NOT EXECUTED offline)
            providers = ["bridge"] if direct else self.f_client.key_order(question.target)  # GLUE (NOT EXECUTED offline)
            provider = next((name for name in providers if name not in attempted), None)  # GLUE (NOT EXECUTED offline)
            if provider is None:  # GLUE (NOT EXECUTED offline)
                if self.f_client.exhausted:  # GLUE (NOT EXECUTED offline)
                    raise CreditExhausted("router")  # GLUE (NOT EXECUTED offline)
                raise SkipQuestion("INVALID_OUTPUT")  # GLUE (NOT EXECUTED offline)
            attempted.add(provider)  # GLUE (NOT EXECUTED offline)
            for model in (BRIDGE if direct else CHEAP):  # GLUE (NOT EXECUTED offline)
                if provider in self.f_client.exhausted:  # GLUE (NOT EXECUTED offline)
                    break  # GLUE (NOT EXECUTED offline)
                timeout = self.f_client.remaining(deadline, 480)  # GLUE (NOT EXECUTED offline)
                self.f_state.parser_calls["calls"] += 1  # GLUE (NOT EXECUTED offline)
                try:  # GLUE (NOT EXECUTED offline)
                    with call_scope(deadline):  # GLUE (NOT EXECUTED offline)
                        parser_model = GeneralLlm(model=("openai/" if direct else "openrouter/") + model,  # GLUE (NOT EXECUTED offline)
                                                  api_key=self.f_env.get(NAMES[provider], ""), timeout=timeout, allowed_tries=1)  # GLUE (NOT EXECUTED offline)
                        answer = await asyncio.wait_for(structure_output(  # GLUE (NOT EXECUTED offline)
                            text, output_type, model=parser_model, num_validation_samples=1,  # GLUE (NOT EXECUTED offline)
                            additional_instructions=instructions), timeout=timeout)  # GLUE (NOT EXECUTED offline)
                        if provider == "own":  # GLUE (NOT EXECUTED offline)
                            self.f_state.alert("USING_OWN_KEY")  # GLUE (NOT EXECUTED offline)
                        return answer  # GLUE (NOT EXECUTED offline)
                except CreditExhausted:  # GLUE (NOT EXECUTED offline)
                    self.f_state.parser_calls["err"] += 1  # GLUE (NOT EXECUTED offline)
                    self.f_client.exhausted.add(provider)  # GLUE (NOT EXECUTED offline)
                    break  # GLUE (NOT EXECUTED offline)
                except Exception as error:  # GLUE (NOT EXECUTED offline)
                    self.f_state.parser_calls["err"] += 1  # GLUE (NOT EXECUTED offline)
                    status = attribute(error, "status_code", 0)  # GLUE (NOT EXECUTED offline)
                    body = attribute(error, "body", {})  # GLUE (NOT EXECUTED offline)
                    if isinstance(body, dict) and "error" not in body:  # GLUE (NOT EXECUTED offline)
                        body = {"error": body}  # GLUE (NOT EXECUTED offline)
                    try:  # GLUE (NOT EXECUTED offline)
                        self.f_client.quota(provider, status, body)  # GLUE (NOT EXECUTED offline)
                    except CreditExhausted:  # GLUE (NOT EXECUTED offline)
                        break  # GLUE (NOT EXECUTED offline)
                    if status in (400, 404):  # GLUE (NOT EXECUTED offline)
                        if model not in self.f_client.unavailable:  # GLUE (NOT EXECUTED offline)
                            self.f_client.unavailable.add(model)  # GLUE (NOT EXECUTED offline)
                            self.f_state.alert("MODEL_UNAVAILABLE")  # GLUE (NOT EXECUTED offline)
                            logger.info("MODEL_UNAVAILABLE model=%s", model)  # GLUE (NOT EXECUTED offline)
                    if status in (401, 403):  # GLUE (NOT EXECUTED offline)
                        raise SkipQuestion("INVALID_OUTPUT") from None  # GLUE (NOT EXECUTED offline)
            if provider not in self.f_client.exhausted:  # GLUE (NOT EXECUTED offline)
                raise SkipQuestion("INVALID_OUTPUT")  # GLUE (NOT EXECUTED offline)

    def parser_fallback(self, question, text, tier=None):  # GLUE (NOT EXECUTED offline)
        async def convert():  # GLUE (NOT EXECUTED offline)
            output_type = BinaryPrediction if question.kind == "binary" else (  # GLUE (NOT EXECUTED offline)
                PredictedOptionList if question.kind == "multiple_choice" else list[Percentile])  # GLUE (NOT EXECUTED offline)
            parsed = await self.structure(question, text, output_type, tier=tier,  # GLUE (NOT EXECUTED offline)
                                          instructions="Use exactly these options and units: " +  # GLUE (NOT EXECUTED offline)
                                          repr(question.options) + " " + question.unit +  # GLUE (NOT EXECUTED offline)
                                          (" Percentiles: " + repr(numeric.LEVELS) if numeric_path.enabled(question, self.f_env, self.f_state) else ""))  # GLUE (NOT EXECUTED offline)
            if question.kind == "binary":  # GLUE (NOT EXECUTED offline)
                return parse.probability(str(attribute(parsed, "prediction_in_decimal")))  # GLUE (NOT EXECUTED offline)
            if question.kind == "multiple_choice":  # GLUE (NOT EXECUTED offline)
                items = attribute(parsed, "predicted_options", [])  # GLUE (NOT EXECUTED offline)
                lines = [str(attribute(p, "option_name")) + ": " + str(attribute(p, "probability")) for p in items]  # GLUE (NOT EXECUTED offline)
                return parse.parse(question, "\n".join(lines))  # GLUE (NOT EXECUTED offline)
            if numeric_path.enabled(question, self.f_env, self.f_state):  # GLUE (NOT EXECUTED offline)
                lines = []  # GLUE (NOT EXECUTED offline)
                for point in parsed:  # GLUE (NOT EXECUTED offline)
                    fraction, value = attribute(point, "percentile"), attribute(point, "value")  # GLUE (NOT EXECUTED offline)
                    if not validate.finite(fraction) or not validate.finite(value):  # GLUE (NOT EXECUTED offline)
                        raise ValueError("invalid percentile")  # GLUE (NOT EXECUTED offline)
                    level = next((level for level in numeric.LEVELS if abs(fraction * 100 - level) <= 1e-6), None)  # GLUE (NOT EXECUTED offline)
                    if level is not None:  # GLUE (NOT EXECUTED offline)
                        lines.append(f"Percentile {level:g}: {numeric.plain(value)}")  # GLUE (NOT EXECUTED offline)
                return numeric.parse_percentiles(question, "\n".join(lines))  # GLUE (NOT EXECUTED offline)
            values = {int(round(attribute(p, "percentile", -1) * 100)): attribute(p, "value") for p in parsed}  # GLUE (NOT EXECUTED offline)
            return parse.parse(question, "\n".join(f"Percentile {p}: {v}" for p, v in values.items()))  # GLUE (NOT EXECUTED offline)
        return self.on_main_loop(convert(), question)  # GLUE (NOT EXECUTED offline)

    def on_main_loop(self, coroutine, question):  # GLUE (NOT EXECUTED offline)
        context = self.f_context.get(question.qid)  # GLUE (NOT EXECUTED offline)
        remaining = max(0, context[3] - self.f_clock.monotonic()) if context else 480  # GLUE (NOT EXECUTED offline)
        future = asyncio.run_coroutine_threadsafe(coroutine, self.f_loop)  # GLUE (NOT EXECUTED offline)
        try:  # GLUE (NOT EXECUTED offline)
            return future.result(timeout=remaining)  # GLUE (NOT EXECUTED offline)
        except FutureTimeout:  # GLUE (NOT EXECUTED offline)
            future.cancel()  # GLUE (NOT EXECUTED offline)
            raise SkipQuestion("TOO_LATE") from None  # GLUE (NOT EXECUTED offline)

    def prepare(self, raw, question, result):  # GLUE (NOT EXECUTED offline)
        if result.numeric_v1:  # GLUE (NOT EXECUTED offline)
            try:  # GLUE (NOT EXECUTED offline)
                percentiles = [Percentile(percentile=f, value=v) for f, v in numeric.sdk_percentiles(question, result.cdf)]  # GLUE (NOT EXECUTED offline)
                distribution = NumericDistribution.from_question(percentiles, raw)  # GLUE (NOT EXECUTED offline)
                if len(distribution.get_cdf()) != question.inbound_outcome_count + 1:  # GLUE (NOT EXECUTED offline)
                    raise ValueError("CDF size")  # GLUE (NOT EXECUTED offline)
                result.prediction = distribution  # GLUE (NOT EXECUTED offline)
                return result  # GLUE (NOT EXECUTED offline)
            except Exception:  # GLUE (NOT EXECUTED offline)
                result.numeric_v1 = False  # GLUE (NOT EXECUTED offline)
                numeric_path.fallback(self.f_state)  # GLUE (NOT EXECUTED offline)
                if "without-numeric" not in result.caps:  # GLUE (NOT EXECUTED offline)
                    result.caps.append("without-numeric")  # GLUE (NOT EXECUTED offline)
        if question.kind == "binary":  # GLUE (NOT EXECUTED offline)
            result.prediction = result.value  # GLUE (NOT EXECUTED offline)
        elif question.kind == "multiple_choice":  # GLUE (NOT EXECUTED offline)
            PredictedOption = attribute(forecasting_tools, "PredictedOption")  # GLUE (NOT EXECUTED offline)
            if PredictedOption is not None:  # GLUE (NOT EXECUTED offline)
                result.prediction = PredictedOptionList(predicted_options=[  # GLUE (NOT EXECUTED offline)
                    PredictedOption(option_name=k, probability=result.value[k]) for k in question.options])  # GLUE (NOT EXECUTED offline)
            else:  # GLUE (NOT EXECUTED offline)
                async def convert():  # GLUE (NOT EXECUTED offline)
                    text = "\n".join(f"{k}: {v}" for k, v in result.value.items())  # GLUE (NOT EXECUTED offline)
                    return await self.structure(question, text, PredictedOptionList, tier=result.tier,  # GLUE (NOT EXECUTED offline)
                                                instructions="Preserve the exact labels and probabilities.")  # GLUE (NOT EXECUTED offline)
                parsed = self.on_main_loop(convert(), question)  # GLUE (NOT EXECUTED offline)
                items = attribute(parsed, "predicted_options", [])  # GLUE (NOT EXECUTED offline)
                values = {attribute(p, "option_name"): attribute(p, "probability") for p in items}  # GLUE (NOT EXECUTED offline)
                if not Gate.matches(question, values, result.value):  # GLUE (NOT EXECUTED offline)
                    raise SkipQuestion("INVALID_OUTPUT")  # GLUE (NOT EXECUTED offline)
                result.prediction = parsed  # GLUE (NOT EXECUTED offline)
        else:  # GLUE (NOT EXECUTED offline)
            values, previous, count = [], None, 0  # GLUE (NOT EXECUTED offline)
            span = question.upper - question.lower  # GLUE (NOT EXECUTED offline)
            for p, value in sorted(result.value.items()):  # GLUE (NOT EXECUTED offline)
                count = count + 1 if value == previous else 0  # GLUE (NOT EXECUTED offline)
                previous = value  # GLUE (NOT EXECUTED offline)
                if count:  # GLUE (NOT EXECUTED offline)
                    value += span * 1e-6 * count  # GLUE (NOT EXECUTED offline)
                    if "tie-break" not in result.caps:  # GLUE (NOT EXECUTED offline)
                        result.caps.append("tie-break")  # GLUE (NOT EXECUTED offline)
                values.append((p, value))  # GLUE (NOT EXECUTED offline)
            percentiles = [Percentile(percentile=p / 100, value=v) for p, v in values]  # GLUE (NOT EXECUTED offline)
            dist = NumericDistribution.from_question(percentiles, raw)  # GLUE (NOT EXECUTED offline)
            get_cdf = attribute(dist, "get_cdf")  # GLUE (NOT EXECUTED offline)
            if not callable(get_cdf):  # GLUE (NOT EXECUTED offline)
                raise SkipQuestion("INVALID_OUTPUT")  # GLUE (NOT EXECUTED offline)
            cdf = [attribute(p, "percentile") for p in get_cdf()]  # GLUE (NOT EXECUTED offline)
            if not question.size_known:  # GLUE (NOT EXECUTED offline)
                question.inbound_outcome_count = len(cdf) - 1  # GLUE (NOT EXECUTED offline)
                logger.info("GLUE-FALLBACK %s.cdf_length", type(raw).__name__)  # GLUE (NOT EXECUTED offline)
            result.cdf = validate.cdf_api(question, cdf)  # GLUE (NOT EXECUTED offline)
            if result.cdf is None:  # GLUE (NOT EXECUTED offline)
                raise SkipQuestion("INVALID_OUTPUT")  # GLUE (NOT EXECUTED offline)
            result.prediction = dist  # GLUE (NOT EXECUTED offline)
        return result  # GLUE (NOT EXECUTED offline)

    def granted_deadline(self, qid, deadline):  # GLUE (NOT EXECUTED offline)
        question, research, tier, old_deadline, urgent = self.f_context[qid]  # GLUE (NOT EXECUTED offline)
        self.f_context[qid] = (question, research, tier, deadline, urgent)  # GLUE (NOT EXECUTED offline)

    async def prediction(self, raw):  # GLUE (NOT EXECUTED offline)
        question = self.standin(raw)  # GLUE (NOT EXECUTED offline)
        try:  # GLUE (NOT EXECUTED offline)
            question = self.question(raw)  # GLUE (NOT EXECUTED offline)
            context = self.f_context.get(question.qid)  # GLUE (NOT EXECUTED offline)
            if context is None:  # GLUE (NOT EXECUTED offline)
                raise SkipQuestion("INVALID_OUTPUT")  # GLUE (NOT EXECUTED offline)
            question, research, tier, end, urgent = context  # GLUE (NOT EXECUTED offline)
            self.f_state.counts["attempted"] += 1  # GLUE (NOT EXECUTED offline)
            self.f_state.mark_seen(question)  # GLUE (NOT EXECUTED offline)
            self.f_state.attempted_by_target[question.target] += 1  # GLUE (NOT EXECUTED offline)
            deps = Dependencies(self.f_client, self.f_clock, self.f_state, self.f_env,  # GLUE (NOT EXECUTED offline)
                                prepare=lambda q, r: self.prepare(raw, q, r), parser=self.parser_fallback,  # GLUE (NOT EXECUTED offline)
                                deadline=end, timeout=300 if urgent else 480,  # GLUE (NOT EXECUTED offline)
                                granted=lambda value: self.granted_deadline(question.qid, value),  # GLUE (NOT EXECUTED offline)
                                evidence=self.f_evidence.get(question.qid))  # GLUE (NOT EXECUTED offline)
            before = await asyncio.to_thread(self.f_pacer.measure_start)  # GLUE (NOT EXECUTED offline)
            try:  # GLUE (NOT EXECUTED offline)
                result = await forecast_async(question, research, tier, deps)  # GLUE (NOT EXECUTED offline)
            finally:  # GLUE (NOT EXECUTED offline)
                await asyncio.to_thread(self.f_pacer.measure_end, question, tier, before)  # GLUE (NOT EXECUTED offline)
            self.f_gate.register(question, result)  # GLUE (NOT EXECUTED offline)
            return ReasonedPrediction(prediction_value=result.prediction, reasoning=result.comment)  # GLUE (NOT EXECUTED offline)
        except SkipQuestion as skip:  # GLUE (NOT EXECUTED offline)
            self.f_state.failure(question.qid, skip.reason)  # GLUE (NOT EXECUTED offline)
            self.f_state.skip(question, skip.reason)  # GLUE (NOT EXECUTED offline)
            raise  # GLUE (NOT EXECUTED offline)
        except Exception:  # GLUE (NOT EXECUTED offline)
            self.f_state.failure(question.qid, "INVALID_OUTPUT")  # GLUE (NOT EXECUTED offline)
            self.f_state.skip(question, "INVALID_OUTPUT")  # GLUE (NOT EXECUTED offline)
            raise SkipQuestion("INVALID_OUTPUT") from None  # GLUE (NOT EXECUTED offline)

    async def _run_forecast_on_binary(self, question, research):  # GLUE (NOT EXECUTED offline)
        return await self.prediction(question)  # GLUE (NOT EXECUTED offline)

    async def _run_forecast_on_multiple_choice(self, question, research):  # GLUE (NOT EXECUTED offline)
        return await self.prediction(question)  # GLUE (NOT EXECUTED offline)

    async def _run_forecast_on_numeric(self, question, research):  # GLUE (NOT EXECUTED offline)
        return await self.prediction(question)  # GLUE (NOT EXECUTED offline)

    async def _run_forecast_on_date(self, question, research):  # GLUE (NOT EXECUTED offline)
        return await self.prediction(question)  # GLUE (NOT EXECUTED offline)

    async def _run_forecast_on_conditional(self, question, research):  # GLUE (NOT EXECUTED offline)
        return await self.prediction(question)  # GLUE (NOT EXECUTED offline)

    async def _aggregate_predictions(self, predictions, question):  # GLUE (NOT EXECUTED offline)
        if len(predictions) == 1:  # GLUE (NOT EXECUTED offline)
            return predictions[0]  # GLUE (NOT EXECUTED offline)
        return await super()._aggregate_predictions(predictions, question)  # GLUE (NOT EXECUTED offline)


async def execute(args, env, clock, state):  # GLUE (NOT EXECUTED offline)
    main_loop = asyncio.get_running_loop()  # GLUE (NOT EXECUTED offline)
    test = args.mode == "test_questions"  # GLUE (NOT EXECUTED offline)
    if test:  # GLUE (NOT EXECUTED offline)
        env = dict(env, MODEL_PRESET=env.get("TEST_PRESET") or "C")  # GLUE (NOT EXECUTED offline)
        state.model_preset = None  # GLUE (NOT EXECUTED offline)
    state.env = env  # GLUE (NOT EXECUTED offline)
    state.loop_min = getattr(args, "loop_minutes", None)  # GLUE (NOT EXECUTED offline)
    state.poll_min = getattr(args, "poll_minutes", None)  # GLUE (NOT EXECUTED offline)
    season = targets.season(env)  # GLUE (NOT EXECUTED offline)
    if not test and not season.valid:  # GLUE (NOT EXECUTED offline)
        state.alert("TARGET_MISMATCH")  # GLUE (NOT EXECUTED offline)
    if not test and not enabled(env, "BOT_ENABLED"):  # GLUE (NOT EXECUTED offline)
        logger.info("DISABLED")  # GLUE (NOT EXECUTED offline)
        return  # GLUE (NOT EXECUTED offline)
    if not test and not targets.active(clock.now(), env):  # GLUE (NOT EXECUTED offline)
        state.alert("SEASON_OVER")  # GLUE (NOT EXECUTED offline)
        return  # GLUE (NOT EXECUTED offline)
    client = Client(env, clock, state.alert)  # GLUE (NOT EXECUTED offline)
    pacer = Pacer(env, client, state, clock)  # GLUE (NOT EXECUTED offline)
    remaining, limit = await asyncio.to_thread(pacer.refresh)  # GLUE (NOT EXECUTED offline)
    logger.info("CREDIT remaining=%s limit=%s source=%s", "unknown" if remaining is None else format(remaining, ".2f"), limit, getattr(client, "credit_source", "unknown"))  # GLUE (NOT EXECUTED offline)
    if not test:  # GLUE (NOT EXECUTED offline)
        counts, reasons = [], []  # GLUE (NOT EXECUTED offline)
        for target in (season.id, MINIBENCH_ID):  # GLUE (NOT EXECUTED offline)
            details = {}  # GLUE (NOT EXECUTED offline)
            counts.append(await asyncio.to_thread(open_count, target, env, details=details))  # GLUE (NOT EXECUTED offline)
            reasons.append(details.get("reason", "error" if counts[-1] == "unknown" else "ok"))  # GLUE (NOT EXECUTED offline)
        state.open = {name: value if isinstance(value, (int, float)) else "unknown:" + reason for name, value, reason in zip(("season", "minibench"), counts, reasons)}  # GLUE (NOT EXECUTED offline)
        if live.startup_counts(counts, reasons):  # GLUE (NOT EXECUTED offline)
            state.alert("POLL_FAILING")  # GLUE (NOT EXECUTED offline)
        for line, reason in zip(targets.startup(*counts, env=env), reasons):  # GLUE (NOT EXECUTED offline)
            logger.info("%s reason=%s", line, reason)  # GLUE (NOT EXECUTED offline)
    tally = webread.Tally()  # GLUE (NOT EXECUTED offline)
    def counted_ask_news(*args, **kwargs):  # GLUE (NOT EXECUTED offline)
        try:  # GLUE (NOT EXECUTED offline)
            value = ask_news(*args, **kwargs)  # GLUE (NOT EXECUTED offline)
            text, count = value  # GLUE (NOT EXECUTED offline)
            if not isinstance(text, str) or not isinstance(count, int):  # GLUE (NOT EXECUTED offline)
                raise ValueError()  # GLUE (NOT EXECUTED offline)
        except Exception as error:  # GLUE (NOT EXECUTED offline)
            state.record_research(False, error_code(error))  # GLUE (NOT EXECUTED offline)
            raise  # GLUE (NOT EXECUTED offline)
        state.record_research(bool(text.strip()))  # GLUE (NOT EXECUTED offline)
        return value  # GLUE (NOT EXECUTED offline)
    research = Service(env, state, counted_ask_news, tally=tally)  # GLUE (NOT EXECUTED offline)
    reader = evidence.call("sources", lambda: SourcesReader(env, clock, tally=tally), SimpleNamespace(read=lambda *a: sources.PagesBrief()), state)  # GLUE (NOT EXECUTED offline)
    web = evidence.call("research2", lambda: WebResearch(env, clock, tally=tally, key_name="OPENROUTER_API_KEY"), SimpleNamespace(brief=lambda *a: research2.WebBrief()), state)  # GLUE (NOT EXECUTED offline)
    market = evidence.call("markets", lambda: Markets(env, clock, tally=tally), SimpleNamespace(snapshot=lambda *a: markets.MarketsBrief()), state)  # GLUE (NOT EXECUTED offline)
    pool = ThreadPoolExecutor(max_workers=8, thread_name_prefix="research")  # GLUE (NOT EXECUTED offline)
    state.evidence_pool = pool  # GLUE (NOT EXECUTED offline)
    gate = Gate(state, env)  # GLUE (NOT EXECUTED offline)
    state.write()  # GLUE (NOT EXECUTED offline)
    install_post_gate(gate)  # GLUE (NOT EXECUTED offline)
    research_limiter = PriorityLimiter(2)  # GLUE (NOT EXECUTED offline)
    def create_bot(target):  # GLUE (NOT EXECUTED offline)
        bot = FBot(research_reports_per_question=1, predictions_per_research_report=1,  # GLUE (NOT EXECUTED offline)
                   enable_summarize_research=False,  # GLUE (NOT EXECUTED offline)
                   use_research_summary_to_forecast=False, publish_reports_to_metaculus=True,  # GLUE (NOT EXECUTED offline)
                   folder_to_save_reports_to=None, skip_previously_forecasted_questions=not test,  # GLUE (NOT EXECUTED offline)
                   extra_metadata_in_explanation=True, llms=model_slots(env))  # GLUE (NOT EXECUTED offline)
        bot.setup(env, state, client, pacer, research, gate, test=test, main_loop=main_loop,  # GLUE (NOT EXECUTED offline)
                  research_limiter=research_limiter)  # GLUE (NOT EXECUTED offline)
        bot.f_evidence_services = (tally, reader, web, market, pool)  # GLUE (NOT EXECUTED offline)
        bot.f_loop_minutes = getattr(args, "loop_minutes", 45)  # GLUE (NOT EXECUTED offline)
        bot.f_target = target  # GLUE (NOT EXECUTED offline)
        return bot  # GLUE (NOT EXECUTED offline)
    bots = {"test": create_bot("test")} if test else {name: create_bot(name) for name in (("season", "minibench") if season.valid else ("minibench",))}  # GLUE (NOT EXECUTED offline)
    bot = bots.get("test")  # GLUE (NOT EXECUTED offline)

    async def poll_with_bot(bot, target, return_exceptions=True):  # GLUE (NOT EXECUTED offline)
        await asyncio.to_thread(pacer.refresh)  # GLUE (NOT EXECUTED offline)
        try:  # GLUE (NOT EXECUTED offline)
            reports = await bot.forecast_on_tournament(target, return_exceptions=return_exceptions)  # GLUE (NOT EXECUTED offline)
        finally:  # GLUE (NOT EXECUTED offline)
            gate.finish_poll(bot.f_questions)  # GLUE (NOT EXECUTED offline)
        await asyncio.to_thread(gate.retry_comments, transport, env)  # GLUE (NOT EXECUTED offline)
        evidence.sync(tally, state)  # GLUE (NOT EXECUTED offline)
        state.write()  # GLUE (NOT EXECUTED offline)
        return reports  # GLUE (NOT EXECUTED offline)

    if test:  # GLUE (NOT EXECUTED offline)
        direct = not env.get("OPENROUTER_API_KEY") and enabled(env, "USE_OPENAI_BRIDGE")  # GLUE (NOT EXECUTED offline)
        models = BRIDGE if direct else PROBES  # GLUE (NOT EXECUTED offline)
        probe_status = {}  # GLUE (NOT EXECUTED offline)
        for model in models:  # GLUE (NOT EXECUTED offline)
            cost = "unknown"  # GLUE (NOT EXECUTED offline)
            try:  # GLUE (NOT EXECUTED offline)
                before_probe = await asyncio.to_thread(client.key)  # GLUE (NOT EXECUTED offline)
                await asyncio.to_thread(client.one, model, "Reply OK", bridge=direct, probe=True)  # GLUE (NOT EXECUTED offline)
                after_probe = await asyncio.to_thread(client.key)  # GLUE (NOT EXECUTED offline)
                cost = max(0, before_probe[0] - after_probe[0]) if before_probe[0] is not None and after_probe[0] is not None else "unknown"  # GLUE (NOT EXECUTED offline)
                status = 200  # GLUE (NOT EXECUTED offline)
            except ModelFailure as failure:  # GLUE (NOT EXECUTED offline)
                status = failure.status  # GLUE (NOT EXECUTED offline)
            except CreditExhausted:  # GLUE (NOT EXECUTED offline)
                status = 402  # GLUE (NOT EXECUTED offline)
            probe_status[model] = status  # GLUE (NOT EXECUTED offline)
            logger.info("COST model=%s usd=%s", model, cost)  # GLUE (NOT EXECUTED offline)
            logger.info("PROBE model=%s status=%s", model, status)  # GLUE (NOT EXECUTED offline)
        if not direct and not any(probe_status.get(model) == 200 for model in FLASH):  # GLUE (NOT EXECUTED offline)
            logger.warning("PROBE_WARNING role=FLASH status=unavailable")  # GLUE (NOT EXECUTED offline)
        await poll_with_bot(bot, TEST_ID)  # GLUE (NOT EXECUTED offline)
        await asyncio.to_thread(gate.retry_comments, transport, env)  # GLUE (NOT EXECUTED offline)
        failed = probe_status.get(BRIDGE[0] if direct else SOL[0]) != 200  # GLUE (NOT EXECUTED offline)
        posted_ok = await asyncio.to_thread(live.check_test_posts, bot.f_questions, state, env, clock, readback)  # GLUE (NOT EXECUTED offline)
        if failed or not posted_ok:  # GLUE (NOT EXECUTED offline)
            raise RuntimeError("TEST_FAILED")  # GLUE (NOT EXECUTED offline)
    else:  # GLUE (NOT EXECUTED offline)
        async def poll_target(name):  # GLUE (NOT EXECUTED offline)
            return await poll_with_bot(bots[name], season.id if name == "season" else MINIBENCH_ID)  # GLUE (NOT EXECUTED offline)
        end = schedule.loop_end(state.started, state.job_started, args.loop_minutes)  # GLUE (NOT EXECUTED offline)
        await schedule.run_targets({name: poll_target for name in bots}, state, clock, end,  # GLUE (NOT EXECUTED offline)
                                   args.poll_minutes, concurrent=schedule.switch(env, "CONCURRENT_TARGETS"))  # GLUE (NOT EXECUTED offline)
        await asyncio.to_thread(gate.retry_comments, transport, env)  # GLUE (NOT EXECUTED offline)
    if not test and schedule.switch(env, "DAILY_PROBE"):  # GLUE (NOT EXECUTED offline)
        try:  # GLUE (NOT EXECUTED offline)
            if probe.due(state.book, clock.now()) and (clock.now() - state.job_started).total_seconds() < 3300 - 165:  # GLUE (NOT EXECUTED offline)
                report = await asyncio.to_thread(probe.run, probe.make_call(client), probe.slots_from_config(config), clock)  # GLUE (NOT EXECUTED offline)
                probe.apply(report, state, state.book, clock.now())  # GLUE (NOT EXECUTED offline)
        except Exception as error:  # GLUE (NOT EXECUTED offline)
            state.without_modules.add("probe")  # GLUE (NOT EXECUTED offline)
            logger.info("MODULE without=probe error=%s", type(error).__name__)  # GLUE (NOT EXECUTED offline)
    evidence.sync(tally, state)  # GLUE (NOT EXECUTED offline)
    pool.shutdown(wait=False, cancel_futures=True)  # GLUE (NOT EXECUTED offline)
    await asyncio.to_thread(pacer.refresh)  # GLUE (NOT EXECUTED offline)
    logger.info("COUNTS posted=%s skipped=%s spend=%s spend_per_question=%s", len(state.posted), sum(state.skips.values()), state.spend(), state.snapshot()["spend_per_question"])  # GLUE (NOT EXECUTED offline)


def main():  # GLUE (NOT EXECUTED offline)
    setup_logs()  # GLUE (NOT EXECUTED offline)
    bot_helpers.check_environment(strict=True)  # GLUE (NOT EXECUTED offline)
    parser = argparse.ArgumentParser()  # GLUE (NOT EXECUTED offline)
    parser.add_argument("--mode", choices=("tournament", "test_questions"), default="tournament")  # GLUE (NOT EXECUTED offline)
    parser.add_argument("--loop-minutes", default="45")  # GLUE (NOT EXECUTED offline)
    parser.add_argument("--poll-minutes", default="10")  # GLUE (NOT EXECUTED offline)
    args = parser.parse_args()  # GLUE (NOT EXECUTED offline)
    args.loop_minutes = runloop.minutes(args.loop_minutes, 45, "LOOP_MINUTES")  # GLUE (NOT EXECUTED offline)
    args.poll_minutes = runloop.minutes(args.poll_minutes, 10, "POLL_MINUTES")  # GLUE (NOT EXECUTED offline)
    clock, env = Clock(), dict(os.environ)  # GLUE (NOT EXECUTED offline)
    state = RunState(clock)  # GLUE (NOT EXECUTED offline)
    try:  # GLUE (NOT EXECUTED offline)
        book = ledger.load()  # GLUE (NOT EXECUTED offline)
    except Exception:  # GLUE (NOT EXECUTED offline)
        book = ledger.empty()  # GLUE (NOT EXECUTED offline)
        state.without_modules.add("ledger")  # GLUE (NOT EXECUTED offline)
    state.attach_book(book)  # GLUE (NOT EXECUTED offline)
    configure_preset(env, state)  # GLUE (NOT EXECUTED offline)
    if env.get("JOB_START"):  # GLUE (NOT EXECUTED offline)
        try:  # GLUE (NOT EXECUTED offline)
            state.job_started = datetime.fromtimestamp(float(env["JOB_START"]), timezone.utc)  # GLUE (NOT EXECUTED offline)
        except (ValueError, OverflowError):  # GLUE (NOT EXECUTED offline)
            logger.info("GLUE-FALLBACK JOB_START")  # GLUE (NOT EXECUTED offline)
    failed = False  # GLUE (NOT EXECUTED offline)
    try:  # GLUE (NOT EXECUTED offline)
        asyncio.run(execute(args, env, clock, state))  # GLUE (NOT EXECUTED offline)
    except Exception as error:  # GLUE (NOT EXECUTED offline)
        logger.warning("RUN status=failed error=%s", type(error).__name__)  # GLUE (NOT EXECUTED offline)
        failed = True  # GLUE (NOT EXECUTED offline)
    finally:  # GLUE (NOT EXECUTED offline)
        if hasattr(state, "evidence_pool"):  # GLUE (NOT EXECUTED offline)
            state.evidence_pool.shutdown(wait=False, cancel_futures=True)  # GLUE (NOT EXECUTED offline)
        log_preset(state)  # GLUE (NOT EXECUTED offline)
        state.write()  # GLUE (NOT EXECUTED offline)
        try:  # GLUE (NOT EXECUTED offline)
            book.prune(clock.now())  # GLUE (NOT EXECUTED offline)
            ledger.save(book, now=clock.now())  # GLUE (NOT EXECUTED offline)
        except Exception as error:  # GLUE (NOT EXECUTED offline)
            logger.info("MODULE without=ledger error=%s", type(error).__name__)  # GLUE (NOT EXECUTED offline)
    raise SystemExit(int(failed))  # GLUE (NOT EXECUTED offline)


if __name__ == "__main__":  # GLUE (NOT EXECUTED offline)
    main()  # GLUE (NOT EXECUTED offline)
