"""Run deliberately broken copies serially under the explicitly supplied temp root."""
import argparse
import ast
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile

MUTATIONS = [('binary_cap', 'fbot/config.py', 'BINARY_CAP = 0.02', 'BINARY_CAP = 0.01', 'tests.test_core'),
 ('cdf_min_step',
  'fbot/validate.py',
  '    minimum_step = 0.01 / n\n',
  '    minimum_step = 0.01 / n * 0.5\n',
  'tests.test_review'),
 ('mc_floor', 'fbot/config.py', 'MC_FLOOR = 0.01', 'MC_FLOOR = 0', 'tests.test_core'),
 ('season_target', 'fbot/config.py', 'SEASON_ID = 33121', 'SEASON_ID = 33122', 'tests.test_release'),
 ('misread_removed',
  'fbot/guards.py',
  'def misread(text):',
  'MISREAD_PATTERNS = ()\n\ndef misread(text):',
  'tests.test_core'),
 ('quota_402_removed', 'fbot/llm.py', 'if status == 402 or', 'if False or', 'tests.test_llm_budget'),
 ('partial_after_exhaustion',
  'fbot/pipeline.py',
  '    if exhausted:\n',
  '    if exhausted and not values:\n',
  'tests.test_pipeline'),
 ('urgent_tier_removed', 'fbot/runloop.py', 'urgent = until_close < 12 * 60', 'urgent = False', 'tests.test_runloop'),
 ('heartbeat_delayed', 'fbot/ops.py', '<= 25 * 86400', '<= 250 * 86400', 'tests.test_ops'),
 ('comment_public', 'fbot/postgate.py', 'is_private=True', 'is_private=False', 'tests.test_integrity'),
 ('test_false_green', 'fbot/ops.py', 'return finish(int(test_failed))', 'return finish(0)', 'tests.test_delivery'),
 ('concurrency_uncapped',
  'fbot/schedule.py',
  'while self._queue and self._active < self._limit:',
  'while self._queue:',
  'tests.test_delivery'),
 ('m13_R01_step_tolerance',
  'fbot/validate.py',
  '    minimum_step = 0.01 / n\n',
  '    minimum_step = 0.01 / n * 0.9\n',
  'tests.test_review'),
 ('m14_R02_exact_comparison',
  'fbot/postgate.py',
  '    def matches(question, actual, wanted):',
  '    def matches(question, actual, wanted):\n        if actual != wanted:\n            return False',
  'tests.test_review'),
 ('m15_R03_unrecorded_gate',
  'fbot/postgate.py',
  '            self.state.skip(registered[0], reason)',
  '            pass',
  'tests.test_review'),
 ('m16_R04_retry_memo_removed',
  'main.py',
  'if self.f_state.failures[question.qid] >= 2:',
  'if False:',
  'tests.test_review'),
 ('m17_R05_gate_reread_removed',
  'fbot/postgate.py',
  'found = self.read(question)',
  'found = False',
  'tests.test_review'),
 ('m18_R06_403_removed',
  'fbot/llm.py',
  '(status == 403 and "key limit exceeded" in str(error.get("message", "")).lower())',
  'False',
  'tests.test_review'),
 ('m19_R07_old_model',
  'fbot/config.py',
  'FLASH = ("google/gemini-3.8-flash", "google/gemini-3.6-flash") + SOL',
  'FLASH = ("google/gemini-3.1-pro-preview", "google/gemini-3.6-flash") + SOL',
  'tests.test_review'),
 ('m20_R09_run_failure_as_skips',
  'fbot/ops.py',
  'alerts.add("RUN_FAILED")',
  'alerts.add("SKIPS")',
  'tests.test_review'),
 ('m21_R10_comment_alert_removed',
  'fbot/postgate.py',
  'self.state.alert("COMMENT_FAILED")',
  'pass',
  'tests.test_review'),
 ('m22_R12_display_raise',
  'fbot/comment.py',
  '    remaining = entries[len(first):]',
  '    if len(first) < len(entries):\n'
  '        raise SkipQuestion("INVALID_OUTPUT")\n'
  '    remaining = entries[len(first):]',
  'tests.test_review'),
 ('m23_R14_old_path_pattern',
  'fbot/comment.py',
  '(?<![A-Za-z])[A-Za-z]:[\\\\/](?!/)[^\\s]*|(?<![\\w.:/-])/(?:home|Users)/[^\\s]*',
  '(?i)(?:[a-z]:[\\\\/]|/home/|/Users/)[^\\s]+',
  'tests.test_review'),
 ('m24_R21_FIFO_limiter', 'fbot/priority.py', 'key = (close, question.qid)', 'key = (0, 0)', 'tests.test_review_v02'),
 ('m25_P01_default_preset_changed',
  'fbot/budget.py',
  '(env.get("MODEL_PRESET") or "auto")',
  '(env.get("MODEL_PRESET") or "A")',
  'tests.test_preset'),
 ('m26_P02_preset_override_removed',
  'fbot/budget.py',
  'self.state.preset_reserve_usd + costs[preset]):\n                tier = preset',
  'self.state.preset_reserve_usd + costs[preset]):\n                pass',
  'tests.test_preset'),
 ('m27_P03_floor_ignored', 'fbot/budget.py', 'and credit - FLOOR_CREDIT >=', 'and credit >=', 'tests.test_preset'),
 ('m28_P03_tier_cost_ignored',
  'fbot/budget.py',
  'self.state.preset_reserve_usd + costs[preset]',
  'self.state.preset_reserve_usd',
  'tests.test_preset'),
 ('m29_P03_pending_reservations_ignored',
  'fbot/budget.py',
  'value - self.reservations.get(name, 0)',
  'value',
  'tests.test_preset'),
 ('m30_P04_MiniBench_override',
  'fbot/budget.py',
  'question.target == "season" and preset in',
  'question.target in ("season", "minibench") and preset in',
  'tests.test_preset'),
 ('m31_P05_bad_preset_alert_removed',
  'fbot/budget.py',
  'state.counts["preset_invalid"] += 1\n            state.alert("PRESET_CONFIG_INVALID")',
  'state.counts["preset_invalid"] += 1',
  'tests.test_preset'),
 ('m32_P05_unknown_preset_not_auto',
  'fbot/budget.py',
  '            preset = "AUTO"',
  '            preset = "A"',
  'tests.test_preset'),
 ('m33_P03_exact_boundary_rejected',
  'fbot/budget.py',
  'and credit - FLOOR_CREDIT >=',
  'and credit - FLOOR_CREDIT >',
  'tests.test_preset'),
 ('m34_P06_run_log_removed', 'main.py', '        log_preset(state)', '        pass', 'tests.test_preset'),
 ('m35_P03_reserve_variable_ignored',
  'fbot/budget.py',
  'float((env.get("PRESET_RESERVE_USD") or "10").strip() or "10")',
  'float("10")',
  'tests.test_preset'),
 ('m36_P07_preset_workflow_binding',
  '.github/workflows/run_bot_on_tournament.yaml',
  'MODEL_PRESET: ${{ vars.MODEL_PRESET }}',
  'MODEL_PRESET: ${{ vars.UNRELATED }}',
  'tests.test_preset'),
 ('m37_P07_reserve_workflow_binding',
  '.github/workflows/run_bot_on_tournament.yaml',
  'PRESET_RESERVE_USD: ${{ vars.PRESET_RESERVE_USD }}',
  'PRESET_RESERVE_USD: ${{ vars.UNRELATED }}',
  'tests.test_preset'),
 ('m38_R24_single_prediction_reaggregated',
  'main.py',
  'if len(predictions) == 1:',
  'if False:',
  'tests.test_review_v02'),
 ('m39_R24_single_prediction_wrapped',
  'main.py',
  '            return predictions[0]',
  '            return predictions',
  'tests.test_review_v02'),
 ('m40_R24_base_aggregator_bypassed',
  'main.py',
  'return await super()._aggregate_predictions(predictions, question)',
  'return predictions[0]',
  'tests.test_review_v02'),
 ('m41_R25_default_user_agent_removed',
  'fbot/llm.py',
  'headers = {"User-Agent": USER_AGENT, **(headers or {})}',
  'headers = dict(headers or {})',
  'tests.test_review_v02'),
 ('m42_R25_caller_headers_dropped', 'fbot/llm.py', '**(headers or {})', '**{}', 'tests.test_review_v02'),
 ('m43_R26_summarization_enabled',
  'main.py',
  'enable_summarize_research=False',
  'enable_summarize_research=True',
  'tests.test_review_v02'),
 ('v1_L1_rest_retry',
  'fbot/ops.py',
  "            self.request('POST', f'/repos/{self.repo}/actions/workflows/run_bot_on_tournament.yaml/dispatches',\n"
  "                         {'ref': branch})",
  '            raise RuntimeError("dispatch")',
  'tests.test_v1_live'),
 ('v1_L2_empty_stop', 'fbot/metadata.py', 'if not data["results"]:', 'if False:', 'tests.test_v1_live'),
 ('v1_L2_plural',
  'fbot/metadata.py',
  '"include_descriptions": "false"',
  '"include_description": "false"',
  'tests.test_v1_live'),
 ('v1_L3_tournament_group_unknown',
  'main.py',
  'if found is None:',
  'if found is None and not question.is_group:',
  'tests.test_v1_live'),
 ('v1_L3_retry',
  'fbot/live.py',
  'retry = read(post_id, ids, env, sleep=clock.sleep, details=details)',
  'retry = states',
  'tests.test_v1_live'),
 ('v1_L3_single_tolerance',
  'fbot/live.py',
  "status == 'unknown' and group and posted and commented",
  "status == 'unknown' and posted and commented",
  'tests.test_v1_acceptance'),
 ('v1_L4_spacing', 'fbot/research.py', 'self.last_start + 2 -', 'self.last_start + 0 -', 'tests.test_v1_live'),
 ('v1_L5_failure', 'fbot/postgate.py', "self.state.failure(qid, 'POST_FAILED')", 'pass', 'tests.test_v1_live'),
 ('v1_M1_budget',
  'fbot/pipeline.py',
  '            deps = replace(deps, deadline=granted.deadline, timeout=granted.timeout)',
  '            raise RuntimeError("budget")',
  'tests.test_v1_ops'),
 ('v1_M2_gate_curve',
  'fbot/postgate.py',
  "entry['continuous_cdf'] = list(result.cdf)",
  'pass',
  'tests.test_v1_numeric'),
 ('v1_M3_prompt_strings',
  'fbot/evidence.py',
  '[block for block in (page_block, market_block) if block]',
  '[("heading", block) for block in (page_block, market_block) if block]',
  'tests.test_v1_research'),
 ('v1_M3_asknews_neutralise',
  'fbot/evidence.py',
  "webread.neutralise, '', state, research.text,",
  "lambda text, markers: text, '', state, research.text,",
  'tests.test_v1_research'),
 ('v1_I1_mini_own',
  'fbot/keys.py',
  'target != "minibench" and own_mode != "off"',
  'own_mode != "off"',
  'tests.test_v1_credit'),
 ('v1_I2_mean',
  'fbot/aggregate.py',
  'median = weighted_median(logits, weights)',
  'median = statistics.mean(logits)',
  'tests.test_v1_credit'),
 ('v1_I2_measure_twentieth',
  'fbot/ledger.py',
  'count >= min_questions else None',
  'count >= min_questions + 1 else None',
  'tests.test_v1_credit'),
 ('v1_H1_48_hours', 'fbot/ledger.py', 'FAILURE_DAYS = 2', 'FAILURE_DAYS = 1', 'tests.test_v1_hardening'),
 ('v1_H2_validate_season',
  'fbot/targets.py',
  'return Season(identity, slug, end, bool(valid))',
  'return Season(identity, slug, end, True)',
  'tests.test_v1_hardening'),
 ('v1_H3_fast_preset',
  'fbot/budget.py',
  '            if fast:\n                tier = "M"',
  '            if fast:\n                tier = preset if preset in ("A", "B", "C") else "M"',
  'tests.test_v1_credit'),
 ('v1_H4_workflow',
  '.github/workflows/run_bot_on_tournament.yaml',
  'NUMERIC_V1: ${{ vars.NUMERIC_V1 }}',
  'NUMERIC_V1: false',
  'tests.test_v1_hardening'),
 ('v1_H5_weekly_own', 'fbot/ops.py', "168 if key == 'USING_OWN_KEY' else 24", '24', 'tests.test_v1_hardening'),
 ('v1_H6_rationale_cap',
  'fbot/hardening.py',
  'per_run = 1500 if len(rationales) >= 4 else 2500',
  'per_run = 2500',
  'tests.test_v1_ops'),
 ('v1_H7_closed_issue',
  'fbot/ops.py',
  "previous = lookup(title, state='all') if lookup else [i for i in issues if i.get('title') == title]",
  'previous = []',
  'tests.test_v1_ops'),
 ('v1_E1_without_ledger',
  'fbot/research.py',
  'loaded = book is not None and book.available',
  'loaded = book is not None',
  'tests.test_v1_edge'),
 ('v1_E1_mini_archive',
  'fbot/research.py',
  'self.parity and self.archive and loaded and question.target == "season"',
  'self.parity and self.archive and loaded',
  'tests.test_v1_edge'),
 ('v1_E2_may_removed', 'fbot/edge.py', '|may|', '|', 'tests.test_v1_edge'),
 ('v1_E2_after_caps',
  'fbot/pipeline.py',
  '        value, shifted = edge.shift(question, value, deps.env)\n'
  '        value, caps = validate.cap_binary(value, values)',
  '        value, caps = validate.cap_binary(value, values)\n'
  '        value, shifted = edge.shift(question, value, deps.env)',
  'tests.test_v1_edge'),
 ('v1_E2_mini',
  'fbot/edge.py',
  "question.target == 'season'",
  "question.target in ('season', 'minibench')",
  'tests.test_v1_edge'),
 ('v1_E2_default_on',
  'fbot/edge.py',
  "'DEADLINE_SHIFT', default=False",
  "'DEADLINE_SHIFT', default=True",
  'tests.test_v1_edge'),
 ('v1_R27_retry', 'fbot/metadata.py', 'sleep(2 * (attempt + 1))', 'sleep(0)', 'tests.test_review_v02'),
 ('v1_R28_error_code',
  'fbot/research.py',
  'return f"{name}:{status}" if isinstance(status, int) else name',
  'return name',
  'tests.test_review_v02'),
 ('v1_R29_sdk_import',
  'main.py',
  'from asknews_sdk import AskNewsSDK',
  'from asknews import AskNewsSDK',
  'tests.test_v1_edge'),
 ('v1_R30_retries',
  'fbot/research.py',
  'for attempt in range(4):',
  'for attempt in range(1):',
  'tests.test_review_v02')]


MUTATIONS.append(('v1_A3_private_comment', 'fbot/postgate.py', 'is_private=True', 'is_private=False', 'tests.test_v1_soak'))
MUTATIONS.append(('v1_I2_outage_table', 'fbot/pipeline.py', 'fallback_runs = TIERS[tier].get("flash_down", ())', 'fallback_runs = ((SOL, 2), (SOL, 2)) if tier == "C" else ()', 'tests.test_v1_credit'))
MUTATIONS.extend([
    ('v1r1_E2_tail_dotstar', 'fbot/edge.py', '[^?]*', '.*', 'tests.test_v1_edge'),
    ('v1r1_E2_left_boundary', 'fbot/edge.py', r'\b(before|by)', '(before|by)', 'tests.test_v1_edge'),
    ('v1r1_E2_label_real', 'tests/fixtures/edge2/deadline_titles.json', '"_label": "SYNTHETIC"', '"_label": "REAL"', 'tests.test_v1_edge'),
    ('v1r1_cap_ignored', 'fbot/llm.py', 'cap = self.caps.get(provider)', 'cap = None', 'tests.test_budget_cap'),
    ('v1r1_cap_usage_not_subtracted', 'fbot/llm.py', 'capped = cap - usage if', 'capped = cap if', 'tests.test_budget_cap'),
    ('v1r1_cap_limit_min_removed', 'fbot/llm.py', 'min(limit, cap)', 'cap', 'tests.test_budget_cap'),
    ('v1r1_own_cap_ignored', 'fbot/llm.py', "'own':self.parse_cap('BUDGET_CAP_OWN_USD')", "'own':None", 'tests.test_budget_cap'),
    ('v1r1_vitals_privacy_filter_removed', 'fbot/ops.py', 'return record  # VITALS_WHITELIST', 'record.update(data); return record  # VITALS_WHITELIST', 'tests.test_vitals'),
    ('v1r1_vitals_escaping_removed', 'fbot/ops.py', "return value.replace('%', '%25').replace('\\r', '%0D').replace('\\n', '%0A')", 'return value', 'tests.test_vitals'),
    ('v1r1_vitals_unknown_model_passed', 'fbot/ops.py', 'name = model_name(raw_name)', 'name = raw_name', 'tests.test_vitals'),
])
MUTATIONS.extend([
    ('v1r2_F1_balance_blanked_during_read', 'fbot/llm.py', '    def key(self, provider="router"):\n', '    def key(self, provider="router"):\n        self.credit(provider, None, None, \'unknown\', None)\n', 'tests.test_budget_cap'),
    ('v1r2_F1_failed_read_source_kept', 'fbot/llm.py', "            self.credit(provider, self.balances.get(provider), None, 'unknown', None)\n", '', 'tests.test_budget_cap'),
])
MUTATIONS.extend([
 ('r3_llm_user_agent_local', 'fbot/llm.py', 'from .webread import USER_AGENT\n',
  'USER_AGENT = "Sextant/0.2 (+https://github.com/devonmvfisher/metac-bot-template)"\n', 'tests.test_r3_terms'),
 ('r3_F09_transient_to_two_day_memory', 'fbot/state.py', 'if reason == "MODEL_TRANSIENT":  # R3S',
  'if False:  # R3S', 'tests.test_r3_f09'),
 ('r3_F09_every_try_counts_as_a_run', 'fbot/state.py', 'if qid not in self.transient_seen:  # R3O',
  'if True:  # R3O', 'tests.test_r3_f09'),
 ('r3_F09_no_cross_run_limit', 'fbot/state.py', '>= TRANSIENT_RUNS:  # R3K', '>= 99:  # R3K', 'tests.test_r3_f09'),
 ('r3_F09_window_ten_times_longer', 'fbot/ledger.py', 'TRANSIENT_HOURS = 3\n', 'TRANSIENT_HOURS = 30\n', 'tests.test_r3_f09'),
 ('r3_F09_429_not_transient', 'fbot/__init__.py', 'self.status in (0, 408, 429)', 'self.status in (0, 408)',
  'tests.test_r3_f09'),
 ('r3_F09_any_transient_run_counts', 'fbot/pipeline.py', 'if transient and transient == len(dropped):  # R3F',
  'if transient:  # R3F', 'tests.test_r3_f09'),
])
# v1-r3 build: rows for the r3 behaviour changes that the decided rows above do not plant a bug in.
MUTATIONS.extend([
 ('r3_deny_checked_after_lookup', 'fbot/webread.py',
  '            if denied(current):  # R3H\n                return Reply("denied")\n'
  '            reason = check_url(current, resolve)  # PB02\n',
  '            reason = check_url(current, resolve)  # PB02\n'
  '            if not reason and denied(current):  # R3H\n                return Reply("denied")\n',
  'tests.test_r3_terms'),
 ('r3_host_look_alike_names', 'fbot/webread.py',
  'return any(host == name or host.endswith("." + name) for name in names)',
  'return any(host.endswith(name) for name in names)', 'tests.test_r3_terms'),
 ('r3_host_trailing_dot_kept', 'fbot/webread.py', 'host = (host or "").lower().rstrip(".")',
  'host = (host or "").lower()', 'tests.test_r3_terms'),
 ('r3_robots_read_off_cleared_hosts', 'fbot/sources.py', 'resolve=self.resolve, allow=self.hosts)  # PB31',
  'resolve=self.resolve)  # PB31', 'tests.test_r3_terms'),
 ('r3_workflow_switch_not_passed', '.github/workflows/test_bot.yaml',
  '          MANIFOLD_ENABLED: ${{ vars.MANIFOLD_ENABLED }}\n', '', 'tests.test_r3_terms'),
 ('r3_F09_outage_not_capped_in_the_run', 'fbot/state.py', '"MODEL_TRANSIENT": 1}', '"MODEL_TRANSIENT": 0}',
  'tests.test_r3_f09'),
 ('r3_F09_prune_keeps_old_marks', 'fbot/ledger.py',
  'if (utc(now) - utc(entry[1])).total_seconds() < TRANSIENT_HOURS * 3600}', 'if True}', 'tests.test_r3_f09'),
 ('r3_F09_sanitize_keeps_bad_ids', 'fbot/ledger.py',
  '_mapping(raw.get("transient")).items()\n                              if _qid(qid) and ',
  '_mapping(raw.get("transient")).items()\n                              if ', 'tests.test_ledger'),
 ('r3_F09_older_ledger_loses_rows', 'fbot/ledger.py', '_mapping(raw.get("transient")).items()',
  'raw["transient"].items()', 'tests.test_r3_f09'),
])

# SEXTANT-POST429: a Metaculus 429 is an outage, not a bad payload.
MUTATIONS.extend([
 ('p429_still_rejected', 'fbot/postgate.py', 'limited = status == 429  # P429B', 'limited = False  # P429B', 'tests.test_post429'),
 ('p429_every_4xx_limited', 'fbot/postgate.py', 'limited = status == 429  # P429B', 'limited = 400 <= status <= 499  # P429B',
  'tests.test_post429'),
 ('p429_alert_ignores_flag', 'fbot/postgate.py', 'if 400 <= status <= 499 and not limited:', 'if 400 <= status <= 499:',
  'tests.test_post429'),
 ('p429_still_invalid_output', 'fbot/postgate.py', '                    elif 400 <= status <= 499:\n',
  '                    if 400 <= status <= 499:\n', 'tests.test_post429'),
 ('p429_not_marked', 'fbot/postgate.py', 'self.rate_limited.add(qid)  # P429C', 'pass  # P429C', 'tests.test_post429'),
 ('p429_finish_ignores_mark', 'fbot/postgate.py', 'if qid in self.rate_limited:  # P429D', 'if False:  # P429D', 'tests.test_post429'),
 ('p429_mark_never_cleared', 'fbot/postgate.py', '                self.rate_limited.discard(qid)\n', '', 'tests.test_post429'),
 ('p429_log_line_removed', 'fbot/postgate.py', 'logger.info("POST_RATE_LIMITED qid=%s kind=%s", qid, kind)', 'pass',
  'tests.test_post429'),
 ('p429_count_removed', 'fbot/postgate.py', 'self.state.counts["post_rate_limited"] += 1', 'pass', 'tests.test_post429'),
 ('p429_no_transient_rule', 'fbot/state.py', 'if reason == "POST_RATE_LIMITED":  # P429A', 'if False:  # P429A', 'tests.test_post429'),
 ('p429_two_day_memory', 'fbot/state.py', 'reason = "MODEL_TRANSIENT"  # a Metaculus 429', 'reason = "POST_FAILED"  # a Metaculus 429',
  'tests.test_post429'),
 ('p429_reason_unknown', 'fbot/__init__.py', '    "POST_RATE_LIMITED",\n', '', 'tests.test_post429'),
 ('p429_retry_readback_benched', 'fbot/postgate.py', 'if qid in self.rate_limited:  # P429E', 'if False:  # P429E',
  'tests.test_post429'),
 ('p429_any_readback_transient', 'fbot/postgate.py', 'if qid in self.rate_limited:  # P429E', 'if True:  # P429E',
  'tests.test_post429'),
])


# v1.1: MiniBench dial, runner pin, dial wiring and the throttle runbook line.
MUTATIONS.extend([
 ('v11_dial_skip_not_a_mode', 'fbot/budget.py', 'if mode not in ("always", "slack", "off", "skip"):', 'if mode not in ("always", "slack", "off"):', 'tests.test_minibench_dial'),
 ('v11_dial_skip_ignored', 'fbot/budget.py', '    if target == "minibench" and mode == "skip":\n', '    if False:\n', 'tests.test_minibench_dial'),
 ('v11_dial_skip_hits_season', 'fbot/budget.py', '    if target == "minibench" and mode == "skip":\n', '    if mode == "skip":\n', 'tests.test_minibench_dial'),
 ('v11_dial_floor_ignored', 'fbot/budget.py', 'and (credit is None or credit < mini_floor):  # MBD1', 'and False:  # MBD1', 'tests.test_minibench_dial'),
 ('v11_dial_floor_unknown_credit_runs', 'fbot/budget.py', '(credit is None or credit < mini_floor)', '(credit is not None and credit < mini_floor)', 'tests.test_minibench_dial'),
 ('v11_dial_floor_inclusive', 'fbot/budget.py', '(credit is None or credit < mini_floor)', '(credit is None or credit <= mini_floor)', 'tests.test_minibench_dial'),
 ('v11_dial_floor_hits_season', 'fbot/budget.py', 'question.target == "minibench" and mini_floor is not None', 'mini_floor is not None', 'tests.test_minibench_dial'),
 ('v11_dial_floor_not_parsed', 'fbot/budget.py', '        state.minibench_floor_usd = floor\n', '        state.minibench_floor_usd = None\n', 'tests.test_minibench_dial'),
 ('v11_dial_floor_negative_accepted', 'fbot/budget.py', 'if not math.isfinite(floor) or floor < 0:', 'if not math.isfinite(floor):', 'tests.test_minibench_dial'),
 ('v11_dial_floor_bad_not_counted', 'fbot/budget.py', '                state.counts["minibench_floor_invalid"] += 1\n', '', 'tests.test_minibench_dial'),
 ('v11_dial_floor_bad_no_alert', 'fbot/budget.py', 'warning("CONFIG MINIBENCH_FLOOR_USD invalid; using no floor")\n                state.alert("PRESET_CONFIG_INVALID")', 'warning("CONFIG MINIBENCH_FLOOR_USD invalid; using no floor")', 'tests.test_minibench_dial'),
 ('v11_dial_preset_ignored', 'fbot/budget.py', '                tier = mini\n', '                pass\n', 'tests.test_minibench_dial'),
 ('v11_dial_preset_reserve_ignored', 'fbot/budget.py', 'and credit >= FLOOR_CREDIT + self.state.preset_reserve_usd + costs[mini]):  # MBD2', 'and True):  # MBD2', 'tests.test_minibench_dial'),
 ('v11_dial_preset_cost_ignored', 'fbot/budget.py', '+ costs[mini]):  # MBD2', '):  # MBD2', 'tests.test_minibench_dial'),
 ('v11_dial_preset_hits_season', 'fbot/budget.py', 'question.target == "minibench" and mini in', 'question.target in ("season", "minibench") and mini in', 'tests.test_minibench_dial'),
 ('v11_dial_preset_invalid_accepted', 'fbot/budget.py', '        if mini not in ("AUTO", "A", "B", "C"):\n', '        if False:\n', 'tests.test_minibench_dial'),
 ('v11_dial_preset_bad_not_counted', 'fbot/budget.py', '            state.counts["minibench_preset_invalid"] += 1\n', '', 'tests.test_minibench_dial'),
 ('v11_dial_preset_not_upper', 'fbot/budget.py', '(env.get("MINIBENCH_PRESET") or "auto").strip().upper()', '(env.get("MINIBENCH_PRESET") or "auto").strip()', 'tests.test_minibench_dial'),
 ('v11_dial_preset_unknown_credit', 'fbot/budget.py', 'and eligible and credit is not None', 'and eligible', 'tests.test_minibench_dial'),
 ('v11_dial_floor_undocumented', 'RUNBOOK.md', '| MINIBENCH_FLOOR_USD |', '| MB_FLOOR |', 'tests.test_minibench_dial'),
 ('v11_pin_review_bot', '.github/workflows/review_bot.yaml', 'runs-on: ubuntu-24.04', 'runs-on: ubuntu-latest', 'tests.test_v11_workflows'),
 ('v11_pin_metaculus_cup', '.github/workflows/run_bot_on_metaculus_cup.yaml', 'runs-on: ubuntu-24.04', 'runs-on: ubuntu-latest', 'tests.test_v11_workflows'),
 ('v11_pin_timer', '.github/workflows/run_bot_on_timer.yaml', 'runs-on: ubuntu-24.04', 'runs-on: ubuntu-latest', 'tests.test_v11_workflows'),
 ('v11_pin_tournament', '.github/workflows/run_bot_on_tournament.yaml', 'runs-on: ubuntu-24.04', 'runs-on: ubuntu-latest', 'tests.test_v11_workflows'),
 ('v11_pin_test_bot', '.github/workflows/test_bot.yaml', 'runs-on: ubuntu-24.04', 'runs-on: ubuntu-latest', 'tests.test_v11_workflows'),
 ('v11_dial_preset_unwired', '.github/workflows/run_bot_on_tournament.yaml', 'MINIBENCH_PRESET: ${{ vars.MINIBENCH_PRESET }}', 'MINIBENCH_PRESET: ${{ vars.UNRELATED }}', 'tests.test_v11_workflows'),
 ('v11_dial_floor_unwired', '.github/workflows/run_bot_on_timer.yaml', '          MINIBENCH_FLOOR_USD: ${{ vars.MINIBENCH_FLOOR_USD }}\n', '', 'tests.test_v11_workflows'),
 ('v11_runbook_throttle_exception_removed', 'RUNBOOK.md', 'is a Metaculus throttle, not a code fault and not a rollback trigger.', 'is a fault.', 'tests.test_v11_post429_http'),
])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--tmp", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    temp = Path(args.tmp).resolve()
    if not temp.is_dir():
        raise SystemExit("Create the job temp folder first.")
    env = dict(os.environ, TEMP=str(temp), TMP=str(temp), PYTHONDONTWRITEBYTECODE="1")
    records = []
    for name, file, old, new, suite in MUTATIONS:
        container = Path(tempfile.mkdtemp(prefix="fbot-mut-" + name + "-", dir=temp)).resolve()
        if not container.is_relative_to(temp):
            raise SystemExit("Mutation path escaped temp root.")
        fork = container / "fork"
        shutil.copytree(root, fork, ignore=shutil.ignore_patterns("__pycache__"))
        path = fork / file
        text = path.read_text(encoding="utf-8")
        if text.count(old) != 1:
            raise SystemExit("Mutation anchor is not unique: " + name)
        changed = text.replace(old, new, 1)
        if path.suffix == ".py":
            ast.parse(changed, feature_version=(3, 11))
        path.write_text(changed, encoding="utf-8", newline="\n")
        completed = subprocess.run([sys.executable, "-B", "tests/run_offline.py", suite], cwd=fork,
                                   env=env, capture_output=True, text=True, timeout=50)
        output = completed.stdout + completed.stderr
        failed = re.findall(r"^(?:FAIL|ERROR): ([^\n]+)", output, re.M)
        killed = completed.returncode != 0 and bool(failed)
        records.append({"mutation": name, "file": file, "suite": suite, "killed": killed,
                        "returncode": completed.returncode, "failed_checks": failed})
        print(name + ": " + ("KILLED" if killed else "SURVIVED"), flush=True)
    Path(args.out).write_text(json.dumps(records, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"Mutations killed: {sum(r['killed'] for r in records)}/{len(records)}")
    raise SystemExit(not all(record["killed"] for record in records))


if __name__ == "__main__":
    main()
