name: Disabled workflow
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
permissions: {}
jobs:
  disabled:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "disabled"
